---
title: "Processing Occurrence Data"
author: "Emily Bellis"
date: "8/31/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Description 
This R markdown document describes cleaning of occurrence data and generation of background points for *Cuscuta* species described in Masanga *et al.* (submitted).  

## Load libraries
```{r}
library(raster)
library(maps)
library(rgdal)
library(rgbif)
library(dplyr)
data(worldMapEnv)
```


## Field data for Kenya collected by Runo lab
```{r}
occ <- read.csv("Cuscuta_georeferenced.csv")
cc <- subset(occ, Cuscuta.Species=="C. campestris")[,1:2]
nrow(cc)
cr <- subset(occ, Cuscuta.Species=="C. reflexa")[,1:2]
nrow(cr)
ck <- subset(occ, Cuscuta.Species=="C. kilimanjari")[,1:2]
nrow(ck)
```

## *C. reflexa*
```{r}
## Get all occurrences 
# no African occurrences in GBIF
map(database="world", regions=c("Kenya","Tanzania","Ethiopia","Uganda","Rwanda","Burundi","Sudan","South Sudan","Eritrea","Somalia","Malawi"))
points(cr$Long, cr$Lat, col="red", pch=20)
```

## *C. kilimanjari*
```{r}
# combine w/GBIF data
#citation: GBIF.org (31 August 2020) GBIF Occurrence Download https://doi.org/10.15468/dl.muwe3t
gbif.ck <- read.csv("C.kilimanjari_GBIF.csv", header = T)
gbif.ck <- gbif.ck %>% filter(decimalLatitude != "NA") %>% select(decimalLatitude, decimalLongitude)
colnames(gbif.ck)<- c('Lat','Long')

ck.all <- rbind(ck, gbif.ck)

map(database="world", regions=c("Kenya","Tanzania","Ethiopia","Uganda","Rwanda","Burundi","Sudan","South Sudan","Eritrea","Somalia","Malawi"))
points(ck.all$Long, ck.all$Lat, col="red", pch=20)
```

## *C. campestris*
```{r}
# combine w/GBIF data
#citation: GBIF.org (31 August 2020) GBIF Occurrence Download https://doi.org/10.15468/dl.y8rtg4
gbif.cc <- read.csv("C.campestris_GBIF.csv", header = T)
gbif.cc <- gbif.cc %>% filter(decimalLatitude != "NA") %>% select(decimalLatitude, decimalLongitude)
colnames(gbif.cc)<- c('Lat','Long')

cc.all <- rbind(cc, gbif.cc)

map(database="world", regions=c("Kenya","Tanzania","Ethiopia","Uganda","Rwanda","Burundi","Sudan","South Sudan","Eritrea","Somalia","Malawi"))
points(cc.all$Long, cc.all$Lat, col="red", pch=20)
```